/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceLocation = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'avgServiceTimeMinutes' : IDL.Nat,
  'currentServingToken' : IDL.Nat,
  'address' : IDL.Text,
  'category' : IDL.Text,
  'nextTokenCounter' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Token = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'tokenNumber' : IDL.Nat,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'serviceId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const QueueStatus = IDL.Record({
  'waitingCount' : IDL.Nat,
  'nextTokenNumber' : IDL.Nat,
  'currentServingToken' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLocation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [ServiceLocation],
      [],
    ),
  'advanceQueue' : IDL.Func([IDL.Nat], [ServiceLocation], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookToken' : IDL.Func([IDL.Nat], [Token], []),
  'cancelToken' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLocation' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceLocation)], ['query']),
  'getLocations' : IDL.Func([], [IDL.Vec(ServiceLocation)], ['query']),
  'getQueueList' : IDL.Func([IDL.Nat], [IDL.Vec(Token)], ['query']),
  'getQueueStatus' : IDL.Func([IDL.Nat], [QueueStatus], ['query']),
  'getToken' : IDL.Func([IDL.Nat], [IDL.Opt(Token)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTokens' : IDL.Func([], [IDL.Vec(Token)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeLocation' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLocation' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [ServiceLocation],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceLocation = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'avgServiceTimeMinutes' : IDL.Nat,
    'currentServingToken' : IDL.Nat,
    'address' : IDL.Text,
    'category' : IDL.Text,
    'nextTokenCounter' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Token = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'tokenNumber' : IDL.Nat,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'serviceId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const QueueStatus = IDL.Record({
    'waitingCount' : IDL.Nat,
    'nextTokenNumber' : IDL.Nat,
    'currentServingToken' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLocation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [ServiceLocation],
        [],
      ),
    'advanceQueue' : IDL.Func([IDL.Nat], [ServiceLocation], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookToken' : IDL.Func([IDL.Nat], [Token], []),
    'cancelToken' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLocation' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceLocation)], ['query']),
    'getLocations' : IDL.Func([], [IDL.Vec(ServiceLocation)], ['query']),
    'getQueueList' : IDL.Func([IDL.Nat], [IDL.Vec(Token)], ['query']),
    'getQueueStatus' : IDL.Func([IDL.Nat], [QueueStatus], ['query']),
    'getToken' : IDL.Func([IDL.Nat], [IDL.Opt(Token)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTokens' : IDL.Func([], [IDL.Vec(Token)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeLocation' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLocation' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [ServiceLocation],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };