/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface QueueStatus {
  'waitingCount' : bigint,
  'nextTokenNumber' : bigint,
  'currentServingToken' : bigint,
}
export interface ServiceLocation {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'avgServiceTimeMinutes' : bigint,
  'currentServingToken' : bigint,
  'address' : string,
  'category' : string,
  'nextTokenCounter' : bigint,
}
export interface Token {
  'id' : bigint,
  'status' : string,
  'tokenNumber' : bigint,
  'userId' : string,
  'createdAt' : bigint,
  'serviceId' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLocation' : ActorMethod<
    [string, string, string, string, bigint],
    ServiceLocation
  >,
  'advanceQueue' : ActorMethod<[bigint], ServiceLocation>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookToken' : ActorMethod<[bigint], Token>,
  'cancelToken' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLocation' : ActorMethod<[bigint], [] | [ServiceLocation]>,
  'getLocations' : ActorMethod<[], Array<ServiceLocation>>,
  'getQueueList' : ActorMethod<[bigint], Array<Token>>,
  'getQueueStatus' : ActorMethod<[bigint], QueueStatus>,
  'getToken' : ActorMethod<[bigint], [] | [Token]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTokens' : ActorMethod<[], Array<Token>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeLocation' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateLocation' : ActorMethod<
    [bigint, string, string, string, string, bigint],
    ServiceLocation
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];